const money=/R\$?\s*([\d.]+(?:,\d{1,2})?)|([\d.]+(?:,\d{1,2})?)\s*R\$/i;
const domain=/\b(?:[a-z0-9-]+\.)+(?:com\.br|com|net|org|br)\b/i;
const headings={"JÁ PAGO":"paid","JA PAGO":"paid","PAGO":"paid","FEITOS":"done","FEITO":"done","FAZER":"todo","A FAZER":"todo","PENDENTES":"todo","PASSO A PASSO DO QUE FOI FEITO":"procedure","PASSO A PASSO":"procedure"};

export function parseUnstructuredText(text){let section="general",id=0;const items=[];for(const raw of String(text).split(/\r?\n/)){const line=raw.trim();if(!line)continue;const heading=normalizeHeading(line);if(headings[heading]){section=headings[heading];continue}if(isStructuralHeading(line)){if(heading!=="SITE")section="general";continue}if(isTableSeparator(line)||/^\|?\s*(ajuste|item|descrição)\b.*\|/i.test(line))continue;const checked=/^[-*]?\s*\[[xX]\]\s*/.test(line),unchecked=/^[-*]?\s*\[\s]\s*/.test(line);let content=line.replace(/^[-*]\s*/,"").replace(/^\[[xX ]\]\s*/,"").replace(/^\|\s*|\s*\|$/g,"").trim();if(!content)continue;if(line.includes("|")&&/^total$/i.test(content.split("|")[0].replaceAll("*","").trim()))continue;const tableCells=content.split("|").map(x=>x.replaceAll("*","").trim()).filter(Boolean);if(tableCells.length>=2&&parseMoneyCents(tableCells[1])>0){items.push(make(id++,tableCells[0],"income",section==="paid"?"paid":"pending",{amount_cents:parseMoneyCents(tableCells[1])}));continue}const amount=parseMoneyCents(content);if(section==="procedure"){items.push(make(id++,stripMoney(content),"procedure","active"));if(amount>0)items.push(make(id++,stripMoney(content),"income","paid",{amount_cents:amount}));continue}if(section==="paid"){items.push(make(id++,stripMoney(content),amount?"income":"task",amount?"paid":"completed",amount?{amount_cents:amount}:{}));continue}if(section==="done"){items.push(make(id++,content,"task","completed"));continue}if(section==="todo"||checked||unchecked){items.push(make(id++,content,"task",checked?"completed":"todo"));continue}const type=classify(content);items.push(make(id++,stripMoney(content),type,type==="income"||type==="expense"?"pending":type==="task"?"todo":"active",amount?{amount_cents:amount}:{}))}return items.slice(0,150)}

function make(id,content,type,status,extra={}){return{id:`detected-${id}`,content,type,status,selected:true,...extra}}
function normalizeHeading(line){return line.replace(/[*#:_!]/g,"").trim().toUpperCase()}
function isStructuralHeading(line){const cleaned=line.replace(/[*#:_!]/g,"").trim();return cleaned.length>=3&&cleaned===cleaned.toUpperCase()&&/[A-ZÁÀÂÃÉÊÍÓÔÕÚÇ]/.test(cleaned)&&!line.startsWith("-")&&!line.startsWith("|")}
function isTableSeparator(line){return /^\|?[\s:|-]+\|?$/.test(line)}
function stripMoney(value){return value.replace(/\(?\s*\d[\d.,]*\s*R\$\s*\)?/gi,"").replace(/\(?\s*R\$\s*\d[\d.,]*\s*\)?/gi,"").trim()}
function classify(line){const s=line.toLowerCase();if(/(decidido|decisão|aprovou|definido|ficou acordado)/.test(s))return"decision";if(/(passo a passo|procedimento|como fazer|instrução)/.test(s))return"procedure";if(money.test(s))return/(paguei|despesa|compra|custo|gastei)/.test(s)?"expense":"income";if(domain.test(s)&&!/(migrar|migração|apontar|configurar)/.test(s))return"domain";if(/(fazer|ajustar|criar|configurar|validar|corrigir|pendente|resolver|alterar|questionar|migrar|migração)/.test(s))return"task";return"note"}
export function parseMoneyCents(value){const found=String(value).match(money);const raw=found?.[1]||found?.[2];if(!raw)return 0;return Math.round(Number(raw.replaceAll(".","").replace(",","."))*100)}
export function extractDomain(value){return String(value).match(domain)?.[0]?.toLowerCase()||""}
