do $$declare ws uuid;cl uuid:='10000000-0000-0000-0000-000000000001';pr uuid:='20000000-0000-0000-0000-000000000001';uid uuid;begin select id into uid from auth.users order by created_at limit 1;if uid is null then raise notice 'Crie um usuário antes de carregar o seed.';return;end if;select workspace_id into ws from public.workspace_members where user_id=uid order by created_at limit 1;insert into public.clients(id,workspace_id,name,email,whatsapp,status,created_by) values(cl,ws,'Companhia da Limpeza','contato@companhiadalimpeza.com.br','(11) 99999-0000','active',uid) on conflict(id) do nothing;insert into public.projects(id,workspace_id,client_id,name,slug,description,status,priority,agreed_value_cents,progress,last_activity_at,created_by) values(pr,ws,cl,'Companhia da Limpeza','companhia-da-limpeza','Reformulação do site e organização da infraestrutura digital.','active','high',112000,64,now()-interval '3 days',uid) on conflict(id) do nothing;
insert into public.tasks(workspace_id,project_id,client_id,title,status,priority,due_at,created_by) values(ws,pr,cl,'Ajustar FAQ','waiting_client','high',now()+interval '1 day',uid),(ws,pr,cl,'Configurar Google Ads','todo','high',now()+interval '4 days',uid),(ws,pr,cl,'Validar formulário','in_progress','medium',now()+interval '2 days',uid);
insert into public.alerts(workspace_id,project_id,client_id,title,type,severity,recommended_action,created_by) values(ws,pr,cl,'Cliente aguardando resposta sobre FAQ','waiting_client','high','Responder ao cliente hoje',uid),(ws,pr,cl,'Renovação do domínio em 21 dias','domain_expiry','medium','Confirmar renovação automática',uid),(ws,pr,cl,'GTM ainda não configurado','integration_pending','medium','Adicionar o container ao site',uid);
insert into public.financial_entries(workspace_id,project_id,client_id,description,entry_type,status,amount_cents,occurred_at,created_by) values(ws,pr,cl,'Entrada do projeto','income','paid',50000,current_date-20,uid),(ws,pr,cl,'Saldo do projeto','income','pending',62000,current_date+10,uid),(ws,pr,cl,'Custo de hospedagem','expense','paid',8000,current_date-15,uid);
insert into public.decisions(workspace_id,project_id,client_id,title,content,status,decided_at,responsible_name,created_by) values(ws,pr,cl,'Estrutura dos domínios','Cliente aprovou manter uma única estrutura para os dois domínios.','current',now()-interval '4 days','Cliente',uid);
insert into public.activities(workspace_id,project_id,client_id,type,description,actor_id,actor_name,created_at) values(ws,pr,cl,'integration_updated','Formulário de contato configurado e enviado para validação.',uid,'Rafael',now()-interval '3 days');
insert into public.domains(workspace_id,project_id,client_id,domain,registrar,expires_at,status,created_by) values(ws,pr,cl,'companhiadalimpeza.com.br','Registro.br',current_date+21,'attention',uid),(ws,pr,cl,'companhiadalimpezabrasil.com.br','Registro.br',current_date+180,'operational',uid),(ws,pr,cl,'locallimpo.com.br','Registro.br',current_date+220,'operational',uid);
insert into public.hosting_accounts(workspace_id,project_id,client_id,provider,plan,status,backup_status,created_by) values(ws,pr,cl,'Hostinger','Business','operational','operational',uid);
insert into public.integrations(workspace_id,project_id,client_id,name,status,created_by) values(ws,pr,cl,'DNS','operational',uid),(ws,pr,cl,'SSL','operational',uid),(ws,pr,cl,'E-mails','operational',uid),(ws,pr,cl,'GTM','pending',uid),(ws,pr,cl,'Google Ads','pending',uid);end$$;
