import { AppShell } from "@/components/app-shell";
import { requireWorkspace } from "@/lib/auth-context";

export const dynamic = "force-dynamic";

const sections = [
  ["Começo recomendado", [["1. Cliente","Cadastre a pessoa ou empresa que contrata o serviço."],["2. Projeto","Crie o trabalho, vincule o cliente, informe valor e prioridade."],["3. Tarefas","Quebre o projeto em ações. O progresso é calculado pelas tarefas concluídas."],["4. Financeiro","Registre entradas, despesas, descontos e vencimentos."],["5. Contexto","Guarde decisões, reuniões, notas, infraestrutura e arquivos no projeto."]]],
  ["Navegação principal", [["Visão geral","Resumo do workspace: projetos, clientes, atrasos, recebimentos e atividades recentes."],["Entrada e agenda","Central do que exige ação agora: tarefas abertas, atrasos, reuniões e cobranças."],["Clientes","Cadastro e histórico central de cada contratante."],["Projetos","Página operacional que reúne progresso, dinheiro, tarefas, decisões e infraestrutura."],["Tarefas","Lista global de atividades de todos os projetos."],["Financeiro","Visão consolidada de receitas, despesas, descontos e resultado."]]],
  ["Memória e operação", [["Decisões","Registra o que foi definido e qual decisão anterior foi substituída."],["Reuniões","Guarda data, participantes, pauta, notas e resumo."],["Notas","Informações de referência que não são tarefas nem decisões."],["Infraestrutura","Domínios, hospedagem, DNS, SSL, e-mail e integrações técnicas."],["Organizar anotações","Interpreta texto solto, permite revisar e importar itens estruturados."],["Caixa de entrada","Captura rápida para classificar depois como tarefa ou nota."],["Procedimentos","Passos repetíveis, checklists e instruções de trabalho."],["Entregáveis","Produtos que precisam ser produzidos, enviados, aprovados ou ajustados."],["Credenciais","Cofre criptografado de senhas e tokens."],["Arquivos","Storage privado com versões pelo mesmo nome lógico."],["Arquivados","Itens fora da rotina, preservados no histórico."]]],
  ["Significado dos números", [["Progresso","Percentual de tarefas concluídas sobre o total do projeto."],["Recebido","Receitas que possuem status Pago."],["Pendente","Valor combinado menos receitas pagas e descontos registrados."],["Despesas","Saídas pagas vinculadas ao projeto."],["Resultado","Receitas pagas menos custos e despesas pagas."],["Atenção","Itens vencidos, próximos do vencimento ou com problema."]]],
  ["Status mais usados", [["A fazer","Ainda não iniciada."],["Em andamento","Está sendo executada."],["Em revisão","Aguarda conferência."],["Aguardando cliente","Depende de resposta ou material do cliente."],["Concluída","Finalizada e contabilizada no progresso."],["Pendente","Aguarda ação ou pagamento."],["Pago","Valor efetivamente pago."],["Vencido","Passou da data prevista."],["Operacional","Verificado e funcionando."],["Atenção","Requer acompanhamento."],["Não verificado","Ainda não foi conferido."],["Arquivado","Preservado no histórico e oculto da rotina."]]],
  ["Boas práticas", [["Uma tarefa é uma ação","Use verbos e deixe claro o próximo passo."],["Uma decisão preserva contexto","Registre o motivo e substitua formalmente decisões antigas."],["Não apague histórico","Arquive registros encerrados."],["Atualize pagamentos","Os painéis dependem do status correto dos lançamentos."],["Proteja o cofre","Não compartilhe nem altere a chave de criptografia."],["Use a busca","Procure registros pelo campo no topo."]]],
];

export default async function HelpPage() {
  await requireWorkspace();
  return <AppShell><div className="content"><div className="eyebrow">Guia de uso</div><h1 className="page-title">Manual do Contexto</h1><p className="subtitle">O que cada área significa e como manter seu trabalho organizado.</p><div className="manual-grid">{sections.map(([title,items]) => <section className="panel manual-section" key={title}><div className="panel-head"><div className="panel-title">{title}</div></div><div className="manual-list">{items.map(([name,description]) => <div className="manual-item" key={name}><strong>{name}</strong><p>{description}</p></div>)}</div></section>)}</div></div></AppShell>;
}
