create extension if not exists pgcrypto;

create type public.workspace_role as enum ('owner','admin','member','viewer');
create type public.project_status as enum ('planned','active','waiting','completed','cancelled','archived');
create type public.task_status as enum ('inbox','todo','in_progress','waiting_client','waiting_third_party','blocked','review','completed','cancelled','archived');
create type public.priority_level as enum ('low','medium','high','urgent');
create type public.alert_status as enum ('open','snoozed','resolved','ignored');
create type public.severity_level as enum ('low','medium','high','critical');
create type public.entry_type as enum ('income','expense','refund','discount','adjustment','tax','service_cost');
create type public.financial_status as enum ('forecast','pending','paid','overdue','cancelled','partially_paid');
create type public.health_status as enum ('operational','attention','pending','error','unverified','not_applicable');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,avatar_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.workspaces(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,owner_id uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table public.workspace_members(workspace_id uuid not null references public.workspaces(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role public.workspace_role not null default 'member',active boolean not null default true,created_at timestamptz not null default now(),primary key(workspace_id,user_id));
create table public.clients(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),name text not null,legal_name text,email text,phone text,whatsapp text,status text not null default 'active',source text,notes text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.projects(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),client_id uuid not null references public.clients(id),name text not null,slug text not null,description text,status public.project_status not null default 'planned',priority public.priority_level not null default 'medium',color text,starts_at date,due_at date,completed_at timestamptz,agreed_value_cents integer not null default 0 check(agreed_value_cents>=0),progress smallint not null default 0 check(progress between 0 and 100),next_action text,last_activity_at timestamptz,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,unique(workspace_id,slug));
create table public.tasks(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),project_id uuid not null references public.projects(id),client_id uuid references public.clients(id),title text not null,description text,status public.task_status not null default 'todo',priority public.priority_level not null default 'medium',starts_at timestamptz,due_at timestamptz,completed_at timestamptz,next_action text,created_by uuid references auth.users(id),assigned_to uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.decisions(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),project_id uuid not null references public.projects(id),client_id uuid references public.clients(id),title text not null,content text not null,reason text,impact text,status text not null default 'current' check(status in('current','superseded','cancelled','pending_confirmation')),decided_at timestamptz not null default now(),responsible_name text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.activities(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),project_id uuid references public.projects(id),client_id uuid references public.clients(id),type text not null,description text not null,actor_id uuid references auth.users(id),actor_name text,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table public.alerts(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),project_id uuid references public.projects(id),client_id uuid references public.clients(id),title text not null,type text not null,severity public.severity_level not null default 'medium',status public.alert_status not null default 'open',source_type text,source_id uuid,recommended_action text,due_at timestamptz,snoozed_until timestamptz,resolved_at timestamptz,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.financial_entries(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),project_id uuid references public.projects(id),client_id uuid references public.clients(id),description text not null,entry_type public.entry_type not null,status public.financial_status not null default 'pending',amount_cents integer not null check(amount_cents>=0),occurred_at date,due_at date,paid_at date,payment_method text,notes text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.domains(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),project_id uuid references public.projects(id),client_id uuid references public.clients(id),domain text not null,registrar text,holder text,current_dns text,registered_at date,expires_at date,auto_renew boolean not null default false,status public.health_status not null default 'unverified',notes text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(workspace_id,domain));
create table public.hosting_accounts(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),project_id uuid references public.projects(id),client_id uuid references public.clients(id),provider text not null,plan text,server text,panel text,url text,renews_at date,cost_cents integer check(cost_cents>=0),status public.health_status not null default 'unverified',backup_status public.health_status not null default 'unverified',notes text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.integrations(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),project_id uuid references public.projects(id),client_id uuid references public.clients(id),name text not null,status public.health_status not null default 'unverified',checklist jsonb not null default '[]',notes text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create index workspace_members_user on public.workspace_members(user_id) where active;
create index clients_workspace on public.clients(workspace_id,status);
create index projects_workspace on public.projects(workspace_id,status,last_activity_at desc);
create index tasks_project on public.tasks(project_id,status,due_at);
create index decisions_project on public.decisions(project_id,status,decided_at desc);
create index activities_project on public.activities(project_id,created_at desc);
create index alerts_project on public.alerts(project_id,status,severity);
create index financial_project on public.financial_entries(project_id,status,due_at);
create index domains_expiry on public.domains(workspace_id,expires_at);

create function public.set_updated_at() returns trigger language plpgsql set search_path='' as $$begin new.updated_at=now();return new;end$$;
do $$declare t text;begin foreach t in array array['profiles','workspaces','clients','projects','tasks','decisions','alerts','financial_entries','domains','hosting_accounts','integrations'] loop execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()',t);end loop;end$$;

create function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$declare ws uuid;begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''));insert into public.workspaces(name,slug,owner_id) values('Meu espaço','espaco-'||substr(new.id::text,1,8),new.id) returning id into ws;insert into public.workspace_members(workspace_id,user_id,role) values(ws,new.id,'owner');return new;end$$;
revoke all on function public.handle_new_user() from public,anon,authenticated;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

grant usage on schema public to authenticated;
grant select,insert,update,delete on all tables in schema public to authenticated;
revoke all on all tables in schema public from anon;

do $$declare t text;begin foreach t in array array['profiles','workspaces','workspace_members','clients','projects','tasks','decisions','activities','alerts','financial_entries','domains','hosting_accounts','integrations'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;

create policy profiles_self_select on public.profiles for select to authenticated using(id=(select auth.uid()));
create policy profiles_self_update on public.profiles for update to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
create schema if not exists private;
revoke all on schema private from public,anon,authenticated;
create function private.is_workspace_member(check_workspace uuid, allowed_roles public.workspace_role[] default array['owner','admin','member','viewer']::public.workspace_role[]) returns boolean language sql stable security definer set search_path='' as $$select (select auth.uid()) is not null and exists(select 1 from public.workspace_members wm where wm.workspace_id=check_workspace and wm.user_id=(select auth.uid()) and wm.active and wm.role=any(allowed_roles))$$;
revoke all on function private.is_workspace_member(uuid,public.workspace_role[]) from public,anon;
grant usage on schema private to authenticated;
grant execute on function private.is_workspace_member(uuid,public.workspace_role[]) to authenticated;
create policy workspace_member_select on public.workspaces for select to authenticated using((select private.is_workspace_member(id)));
create policy workspace_owner_update on public.workspaces for update to authenticated using(owner_id=(select auth.uid())) with check(owner_id=(select auth.uid()));
create policy members_same_workspace_select on public.workspace_members for select to authenticated using((select private.is_workspace_member(workspace_id)));

do $$declare t text;begin foreach t in array array['clients','projects','tasks','decisions','activities','alerts','financial_entries','domains','hosting_accounts','integrations'] loop execute format('create policy %I on public.%I for select to authenticated using((select private.is_workspace_member(workspace_id)))',t||'_select',t);execute format('create policy %I on public.%I for insert to authenticated with check((select private.is_workspace_member(workspace_id,array[''owner'',''admin'',''member'']::public.workspace_role[])))',t||'_insert',t);execute format('create policy %I on public.%I for update to authenticated using((select private.is_workspace_member(workspace_id,array[''owner'',''admin'',''member'']::public.workspace_role[]))) with check((select private.is_workspace_member(workspace_id,array[''owner'',''admin'',''member'']::public.workspace_role[])))',t||'_update',t);execute format('create policy %I on public.%I for delete to authenticated using((select private.is_workspace_member(workspace_id,array[''owner'',''admin'']::public.workspace_role[])))',t||'_delete',t);end loop;end$$;
